# fly.toml app configuration file generated for bazaar-phx on 2024-01-31T18:20:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bazaar-phx'
primary_region = 'ewr'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'bazaar-phx.fly.dev'
  PORT = '4000'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
